# This is a basic workflow to help you get started with Actions

name: Getting started

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo what is in this directory,
          ls -a
          echo is java installed?
          java -version
          echo
          echo is node installed?
          node -v
          echo
          echo is git installed?
          git --version
          echo
          echo is python installed?
          python --version
          echo what is the workspace locations ?
          echo
          echo $RUNNER_WORKSPACE
          echo who is runing this script?
          whoami
          echo
          echo how is the disc laid out?
          df
          echo 
          echo what is enviroment variables ae avalible ?
          env
          echo runing shell file.....
          sleep 2
          sh ./file.sh


